# Generated by Django 2.2.5 on 2019-09-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profess', '0002_auto_20190906_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_content',
            field=models.TextField(),
        ),
    ]
